require("bandrw.packer")
require("bandrw.common")
require("bandrw.remap")
require("bandrw.telescope")
require("bandrw.colorscheme")
require("bandrw.treesitter")
require("bandrw.gitsigns")
require("bandrw.diffview")
require("bandrw.lualine")
require("bandrw.formatting")
require("bandrw.linting")
require("bandrw.lsp")
require("bandrw.autopairs")
require("bandrw.smart-backspace")

vim.cmd("language en_US")
