require("bandrw.packer")
require("bandrw.common")
require("bandrw.remap")
require("bandrw.nvim-tree")
require("bandrw.telescope")
require("bandrw.colorscheme")
require("bandrw.treesitter")
require("bandrw.gitsigns")
require("bandrw.diffview")
require("bandrw.lualine")
require("bandrw.formatting")
require("bandrw.linting")
require("bandrw.lsp")
require("bandrw.autopairs")
require("bandrw.smart-backspace")
require("bandrw.harpoon")
require("bandrw.codex")

vim.cmd("language en_US")
vim.cmd("lang en_US.UTF-8")
