local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>fs", builtin.live_grep, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fr", builtin.resume, { desc = "Telescope resume" })

vim.keymap.set("n", "]q", ":cnext<CR>zz",  { silent = true, desc = "Next quickfix" })
vim.keymap.set("n", "[q", ":cprev<CR>zz",  { silent = true, desc = "Prev quickfix" })
vim.keymap.set("n", "<leader>qo", ":copen<CR>",  { silent = true, desc = "Open quickfix" })
vim.keymap.set("n", "<leader>qc", ":cclose<CR>", { silent = true, desc = "Close quickfix" })
